# Generated by Django 5.0.4 on 2024-04-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('citizenship', models.CharField(max_length=100)),
                ('matches', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='players/images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
