# Generated by Django 5.0.4 on 2024-04-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_player_delete_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
